### ISSUE TITLE
[UWP] Promise returned by  PSPDFKit.Present(<path>); does not always resolve/reject

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#212]
# Details

I wanted to update our demo application to be have a reproducable demo of #188. However in the demo application the promise returned by `Present` is never resolved nor rejected.

Steps to reproduce

General:

1. clone https://github.com/leoek/react-native-pspdfkit-demo
2. Checkout the branch  #[reproduce-issue-`issueid`](https://github.com/leoek/react-native-pspdfkit-demo/tree/reproduce-issue-212)
2. install dependencies with yarn: yarn
3. install windows vsix extension version 1.11

Issue specific:

1. Click on "Go To PdfScreen"
2. observe in the log that the promise is never resolved nor rejected.

# Acceptance Criteria

- [ ] The promise returned by `Present` should always resolve or reject
- [ ] Every returned promise should resolve or reject (not issue specific)

**Comment by nickwinder** [comment]
Thanks for the reproduction steps. 
I've followed and it produced the following. 
![promiseReturned](https://user-images.githubusercontent.com/16980993/56313743-96453600-6110-11e9-86a6-2f8f7e0412c3.PNG)

Which looks like the promise is returning fine, according to this line. https://github.com/leoek/react-native-pspdfkit-demo/blob/0648f774875e2676a3fb4876208a3a7000375bd8/src/components/PDFView.js#L185

Note, I did change the project to reference https://github.com/PSPDFKit/react-native/tree/1.23.7 to ensure we had a stable test point against the `PSPSDFKit` repo.

We can also see from the `PSPDFKit` Catalog that a promise is returned by running the example. https://github.com/PSPDFKit/react-native/blob/659f9da741d7c856d1b799f143983173240fa4cc/samples/Catalog/Catalog.windows.js#L103-L109

**Comment by leoek** [comment]
@nickwinder 

yes that seems like you got the observed behavior. In our production app I didn't have that issue before and it just happend in the demo application.

Thanks for testing, I will check again whether it works for me with 1.23.7.

**Comment by leoek** [comment]
@nickwinder I can confirm that the issue is gone with version 1.23.7 and sdk 1.12

This seemed to be specific to 1.23.6 + 1.11

**Comment by nickwinder** [comment]
For continuity, I decided to test 1.23.6 + 1.11. This was https://github.com/leoek/react-native-pspdfkit-demo/tree/reproduce-issue-212 with no changes. 

I received the following correct output, so there must have been an issue elsewhere. 
![promiseReturned](https://user-images.githubusercontent.com/16980993/56361319-4b74fe00-61a4-11e9-9e78-93601535f79d.PNG)

**Comment by leoek** [comment]
@nickwinder 

I checked again and managed to reproduce it on 1.23.6 and 1.23.7 now. 

These seem to be the conditions:

1. react-native component is mounted, without a pdf being presented (User enters pdf screen)
2. setToolbarItems is called and fails with `Exception while trying to SetToolbarItemsInWebAsync: Instance is undefined`
3. react-native component is unmounted (User leaves the pdf screen)
4. react-native-component is mounted (User enters pdf screen)
4. `Present` is called and wont resolve any more.

I will try to update the demo application to consistently reproduce these steps.

**Comment by leoek** [comment]
Hi @nickwinder I updated the demo application, the new steps to reproduce are these:

General:

clone https://github.com/leoek/react-native-pspdfkit-demo

1. Checkout the branch `reproduce-issue-212`
2. install dependencies with yarn: yarn
3. install windows vsix extension version 1.12

Issue specific:

1. Click on "Go To PdfScreen"
2. Click on "Back" (top left)
3. Click on "Go To PdfScreen"
4. Click on "Back" (top left)
5. Click on "Go To PdfScreen"
6. observe in the log that the promise is never resolved nor rejected.

**Comment by nickwinder** [comment]
@leoek I apologize it seems I replied to the wrong issues. Please see https://github.com/PSPDFKit/react-native/issues/188#issuecomment-484657653 comment for the issue I receive on the `reproduce-issue-212` branch.

**Comment by leoek** [comment]
Did you follow the steps to reproduce from this [coment ](https://github.com/PSPDFKit/react-native/issues/212#issuecomment-484520856)?

I have added that the pdf is not downloaded for the first two times the screen is entered (instead a dummy promise is rejected [here ](https://github.com/leoek/react-native-pspdfkit-demo/blob/09bb103f6052d397972c520581f984502cc651ad/src/screens/PDFScreen.js#L97)), to trigger the case described [here](https://github.com/PSPDFKit/react-native/issues/212#issuecomment-484503519).

Therefore the download is supposed to fail with the 'skipping the first loads' message the twice.

**Comment by nickwinder** [comment]
I understand now.

I've been digging with this and it seems everything drops when `PDFView.OpenStorageFileAsync` is called in c#. The reason why this works first time is that this method is not called on first pass as the PDFView is not initialized when `Present` is called. Therefore the file is just staged to be shown when the PDFViewe is initialized. This first path seems to work fine, but subsequent calls are failing. 

I'll dig further.

**Comment by leoek** [comment]
@nickwinder Any progress on this issue?

**Comment by nickwinder** [comment]
@leoek I've been able to reproduce it in your demo application. I was trying to make a more minimal application to understand in which area the issue lies, as there are many abstractions in the demo application already. 
As you can see from https://github.com/PSPDFKit/react-native/pull/217 I was trying to mimic the behavior you were seeing, but this seems to be working fine. Any more information is always welcome.

**Comment by leoek** [comment]
@nickwinder 

I think these steps: https://github.com/PSPDFKit/react-native/issues/212#issuecomment-484503519 describe the case very good. These are the conditions I used as basis for the demo.

Any abstractions about the annotations are probably irrelevant for this issue. (Big parts from the PdfView Component are copied from our production application, which makes it easier to create the conditions which lead to errors in our app)

**Comment by nickwinder** [comment]
@leoek 
The tricky part here is that the example we're working with was actually displaying more than one issue. 
I tracked down an issue with the toolbar items to find that `Exception while trying to SetToolbarItemsInWebAsync: Instance is undefined` is not ok and could lead to the PDFview to be in an undefined state, and therefore unable to continue with any commands. So I found a fix for that and I am pushing this through the QA for PSPDFKit for Windows to land the fix in the react native wrapper which will fix the step described https://github.com/PSPDFKit/react-native/issues/212#issuecomment-484503519. I'll keep you updated with this.

I have retested this fix with https://github.com/PSPDFKit/react-native/issues/212#issuecomment-484520856 but this still does not work, therefore there is more at play here. 
I recreated what you have described in a more simple branch of the Catalog https://github.com/PSPDFKit/react-native/pull/217 and this works ok. 

Once we have a fix to you for `Instance is undefined` issue I would encourage you to create a more simplified example and maybe even build upon https://github.com/PSPDFKit/react-native/pull/217 to keep the issue well encapsulated and with minimal external influences. https://github.com/leoek/react-native-pspdfkit-demo is too large a project to debug in a well-encapsulated environment, which was seen with the confusion with `Instance is undefined`.

**Comment by leoek** [comment]
@nickwinder 

I can only try to make the examples in the demo application as clear as possible. This is not easy though...

I get bug reports from the QA of our app which mac describe pretty specific cases. (For example a pdf which was just downloaded and which has a set of annotations which were partly created on ios and partly created on windows). I than try to simulate these real world situations in the demo application to give you a way to reproduce these issues. (which can be pretty time consuming already)

To make the situations which appear in our app and the demo app comparable PdfView.js is mostly identical to our app. All the other files are there to enable us to mimic the situations which can appear during real world usage. 

The following quote about the abstractions is from here: https://github.com/PSPDFKit/react-native/issues/220#issuecomment-490006466

>The PdfView Component needs many abstractions to be usable on all platforms because of different apis between windows and ios/android. Also some of the code is just there to avoid timing issues and crashes we were experiencing when using the methods from the wrapper directly. Also we need to keep track of the state the PdfView is in/was in because it is not reset if the component is unmounted and mounted again (at least on windows).

>I know that it isn't optimal to have the windows complexity and code to reproduce other issues in there. However we can't build a new demo application for every issue we encounter. (Currently PdfView.js can be copied mostly from our app and all the rest of the implementation around it is there to mimic situations which can happen for us in real world usage)

Afterwards I try to minimize the steps without breaking the reproducible demo, but especially for timing issues this can be hard.

**Comment by leoek** [comment]
@nickwinder is this fixed?

**Comment by nickwinder** [comment]
@leoek That was automation for an internal repository. As discussed it is still making its way through QA.

**Comment by leoek** [comment]
@nickwinder do you have an estimate when this will be through?

**Comment by nickwinder** [comment]
PSPDFKit for Windows 2.0 was just release so fixes are propagating their way through now. 
https://github.com/PSPDFKit/react-native/pull/223

**Comment by nickwinder** [comment]
@leoek Just to let you know. I tested this with the new version, but it seems a `Page` lifetime issue is stopping this issue from being closed out. I'll look into a fix for this.

**Comment by nickwinder** [comment]
@leoek I've just merged a fix for the lifetime issue seen here. I tried with https://github.com/leoek/react-native-pspdfkit-demo and it seemed to fix the issue. Grab the latest 1.23.14 and see what you think.

**Comment by leoek** [comment]
@nickwinder I am still experiencing this issue with 2.0 and 1.24.2.

However there is a difference: If I remember correctly only the promise did not resolve in the old version but the PdfView still loaded. Now the promise does not resolve and the PdfView is not loading as well.

**Comment by leoek** [comment]
@nickwinder Should we create a new issue for this?

**Comment by nickwinder** [comment]
Hey, I tested this again with PSPDFKit for Windows 2.2 and 1.24.3 and it works fine. See the GIF for an example of this. 
![pspdfkitdemo-2019-07-01-09-22-16](https://user-images.githubusercontent.com/16980993/60451932-26f4c380-9be2-11e9-86a4-57f9583e23d6.gif)

**Comment by leoek** [comment]
Ok, maybe I need to update our demo application. (I encountered the issue in the main app.)
