### ISSUE TITLE
[UWP] Tooltips are not translated.

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#226]
# Details

Tooltips in the Toolbar are not translated. They are always in English. 

<img width="1595" alt="Screenshot 2019-05-23 at 14 04 24" src="https://user-images.githubusercontent.com/9424038/58251422-e3e23d80-7d63-11e9-81e5-b0076edb034a.png">

# Acceptance Criteria

- [ ] Tooltips are translated. (Same behaviour as any other label)

**Comment by nickwinder** [comment]
@leoek Thanks for reporting this. It seems that this issue propagates all the way through to the Web SDK. For this reason I've filed an issue for you in Zendesk and attached your information. You will get an update there when the issue is resolved.

**Comment by Elmatoss** [comment]
@nickwinder  Do you have a time estimate on this? There wasn't an update on the Zendesk issue on quite a while.

**Comment by nickwinder** [comment]
@Elmatoss Thanks. Replied on Zendesk.

**Comment by nickwinder** [comment]
As you can see the react-native-pspdfkit wrapper as been updated for windows 2.2.0. 
I tested and the issue is resolved. So as soon as PSPDFKit for Windows 2.2.0 is released you're free to update. Thanks!

**Comment by leoek** [comment]
Hi @nickwinder I just udpated to windows 2.2 and the issue is still there for me. Any ideas?

**Comment by nickwinder** [comment]
What language are you using? I tried German and all came out fine. It's also worth cleaning out the project to ensure all changes are taken.

**Comment by leoek** [comment]
@nickwinder 

Ah it will use the windows displaying language. If I use German as the default Windows Language the Tool tips are translated.

I thought it would consider the language defined in the manifest of the app and use that one. Using the system language seems fine for now.

**Comment by nickwinder** [comment]
Ok. This is a UWP/Windows defined directive. Language detection does get complicated, but it will make the best guess possible. https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/manage-language-and-region has some good (but long) information on this. I suppose it would be possible to set "Primary Language Override" on your Windows project if you wanted to have the language fixed.

**Comment by leoek** [comment]
Thanks for the background info. We'll consider this.
