### ISSUE TITLE
[Android] Calling enterAnnotationCreationMode fails with an error.

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#247]
# Details

Calling `enterAnnotationCreationMode` fails with the following exception on android: `reactNative.UIManager.getViewManagerConfig is not a function`

Steps To Reproduce:
1. clone https://github.com/leoek/react-native-pspdfkit-demo
2. checkout `reproduce-issue-247-enterAnnotationCreationMode`
3. `yarn`
4. `yarn android`
5. Press "Go To PdfScreen"
--> The described Exception is thrown.
--> The Viewer did not enter the annotation creation mode

Observed with 1.24.3

# Acceptance Criteria

- [ ] The pspdfkit viewer enters the annotation creation mode if `enterAnnotationCreationMode` is called.
- [ ] There is no exception
- [ ] The changed state is reported through `onStateChanged`

**Comment by leoek** [comment]
@irgendeinich I just noticed that calling `addAnnotation` produces the same error.

**Comment by irgendeinich** [comment]
Thanks for providing the sample project. 
You need to update your `react-native` dependency to `0.59.9`. This should fix the error you're encountering.

**Comment by leoek** [comment]
@irgendeinich this wont be possible and it was even discussed in your own PR: https://github.com/PSPDFKit/react-native/pull/193#pullrequestreview-249469579

It has to work with the versions specified in the peerDependencies: https://github.com/PSPDFKit/react-native/blob/93c78141ad84b6520d932a454da0939dab3f26c0/package.json#L27

**Comment by leoek** [comment]
@irgendeinich There is still an issue with `enterAnnotationCreationMode`. With #248 I can enter the mode successfully if js remote debugging is activated. However the whole app crashes if it is not.

**Comment by leoek** [comment]
I get the following error in the adb log (there is no js error):
```
07-10 19:32:56.497  1740  1740 I Zygote  : Process 8371 exited due to signal (9)
07-10 19:32:56.499  1892  1999 W InputDispatcher: channel '320725a com.appname/com.appname.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-10 19:32:56.499  1892  1999 E InputDispatcher: channel '320725a com.appname/com.appname.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

07-10 19:32:56.512  1892  2204 I ActivityManager: Process com.appname (pid 8371) has died: fore TOP 
07-10 19:32:56.513  1892  1914 W libprocessgroup: kill(-8371, 9) failed: No such process
07-10 19:32:56.513  1892  1914 I libprocessgroup: Successfully killed process cgroup uid 10091 pid 8371 in 0ms
07-10 19:32:56.515  1892  4513 I WindowManager: WIN DEATH: Window{320725a u0 com.appname/com.appname.MainActivity}
07-10 19:32:56.517  1892  2204 W ActivityManager: Force removing ActivityRecord{acf98d9 u0 com.appname/.MainActivity t113}: app died, no saved state
07-10 19:32:56.518  1892  4513 W InputDispatcher: Attempted to unregister already unregistered input channel '320725a com.appname/com.appname.MainActivity (server)'



07-10 19:32:56.560  1739  2037 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{46517f token=Token{bcc629e ActivityRecord{acf98d9 u0 com.appname/.MainActivity t113}}}#0
```

**Comment by irgendeinich** [comment]
Sadly I wasn't able to reproduce this error, both in `debug` and `release` builds this is working properly for me. I also tried it with both remote JS debugging on and off and also no luck in reproducing.
The log also doesnt't contain anything I could use to debug this issue. 

Do you have any more information I could use to reproduce this?

**Comment by leoek** [comment]
@irgendeinich I am not sure how that error was triggered. (It seems to be gone now and I cannot reproduce it any more..)

I guess it's best to close this issue as it was resolved by #248 and create a new one in case that error appears again.

**Comment by irgendeinich** [comment]
Thanks for the update, since the error isn't appearing right now I'm going to close this issue.
If it reappears feel free to open a new one.
